version: '3.8'
services:
  mi-script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contenedor_py3
    volumes:
        - .:/app
    working_dir: /app
    command: python s09_e01.py